### ISSUE TITLE
Should GceInstanceConfig not include name and zone?

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#106]
Thinking through the scenarios where the user wants to create multiple VMs of the same model, but with either different names or in different zones. Is that a valid scenario? If so, would it not be easier to do that with an instance config and then precising name and zone in the Add-GCEInstance cmdlet?

**Comment by ILMTitan** [comment]
The way to write this right now would be something like:
$configList = $nameList | New-GceInstanceConfig ...<Parameters>...
$zoneList | % {
$configList | New-GceInstance -Zone $_
}
