### ISSUE TITLE
Create a Google Cloud Storage PowerShell provider

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#11]
Facts:

1. PowerShell providers are cool.
1. A GCS provider would we awesome.
1. Including it in this repository would be radical.
1. This is a tracking issue.

**Comment by ILMTitan** [comment]
FYI anyone reading these comments, the convention is no longer '<name>_$folder$'. It is now simply `<name>/`.
