### ISSUE TITLE
Support Set-GceInstance -AddDisk $diskobject -Instance $instanceobject

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#114]
Any reason why this is not supported?
What if I want to attach a disk which is in a zone different from the instance?

**Comment by ILMTitan** [comment]
You arne't allowed to attach a disk from a different zone.

**Comment by YnR** [comment]
Fair enough

**Comment by YnR** [comment]
Did not mean to close. It should still accpet object params and throw an error if they are in a different zone, no?

**Comment by ILMTitan** [comment]
AttachDisk already does. Working on making RemoveDisk take a Disk object.
