### ISSUE TITLE
Consolidate Add/Remove GCSObject GCSBucket

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#120]
**Currently**
`New-GCSObject` and `Remove-GCSObject`
`New-GCSBucket` and `Remove-GCSBucket`

**Expected**
`Add-GCSObject` and `Remove-GCSObject`
`Add-GCSBucket` and `Remove-GCSBucket`

**Comment by ILMTitan** [comment]
From the userstudy, this didn't hang anyone up. People had opinions on what it should be, but they found it anyway. I am closing this issue.
