### ISSUE TITLE
Read-GCSObject Remove-GCSObject should get bucket from the piped GCSObject

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#127]
Currently: `Find-GcsObject -Bucket ynrpizza | Read-GcsObject` asks for a bucket, where I assumed it was passed by the GcsObject.

Same behavior with Remove-GCSObject

**Comment by ILMTitan** [comment]
Remove-GcsObject was fixed in PR #77.

**Comment by ILMTitan** [comment]
Read-GcsObject fixed in PR #178.
