### ISSUE TITLE
Set up CI/CD system

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#142]
We should set up a nightly build system to run all Pester tests and if successful upload a zip of the bits to GCS.

**Comment by chrsmith** [comment]
What is the status of this? IIRC you spent some time setting something up. Is it done? (If so, where are the bits?)

**Comment by quoctruong** [comment]
Added Appveyor with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/360
