### ISSUE TITLE
BootstrapGoogleCloudPowerShell.ps1 fails

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#160]
**REPRO**
On GCP Windows Server 2012 R2 instance.
Download https://storage.googleapis.com/g-cloudsharp-unsignedbinaries/powershell/powershell-0.1.2.zip
Right click on zip file to unblock security review
Unzip file
Navigate to content of unzipped folder (for me C:\Users\ynr\Downloads\GoogleCloudPowerShell>)
in PowerShell (Admin mode), run ./BootstrapGoogleCloudPowerShell.ps1 contained in the unzipped folder

**CURRENT**
Shell shows one line with Google Cloud PowerShell, and the command invite prompt.
Current PowerShell (PS) instance can find GCP cmdlets
New PS Instances cannot find GCP cmdlets
$error shows:
```
Import-Module : The specified module 'PSReadline' was not loaded because no valid module file was found in any module
directory.
    + CategoryInfo          : ResourceUnavailable: (PSReadline:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```                

![image](https://cloud.githubusercontent.com/assets/1758462/17112381/b18bfe84-525a-11e6-8e11-613bd4179028.png)

**EXPECTED**
Error message is visible after running the script
GCP cmdlets are accessible in any subsequent session for any user on the machine

**Comment by chrsmith** [comment]
@YnR What does `Get-SecurityPolicy` tell you? Does it work if you run PowerShell as an administrator or if you `Set-SecurityPolicy` to `RemoteUnsigned`?

From the error message it looks like a path / local-directory problem, but you started it from the right folder.

**Comment by YnR** [comment]
I can Set-ExecutionPolicy to unrestricted in an admin window, and the error is still there afterwards. I do not have a Set-SecurityPolicy command available in my PowerShell instance.

**Comment by ILMTitan** [comment]
I just ran this on Yann's test machine and it seemed to work. I am closing this for now.
