### ISSUE TITLE
Code examples on GitHub doc do not match latest bits

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#179]
Could not copy-paste-run Compute examples

1. Add the $vmname  = "my-vm-name" command
2. Correct the disk image bug (currently does not resolve the string)

**Comment by chrsmith** [comment]
@YnR to be clear, you are talking about this page, right?
http://googlecloudplatform.github.io/google-cloud-powershell/#/

@ILMTitan could you please update the snippet to whatever the current, concise way to access disk images is? The file you need to change is here:
https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/master/website/content/home.html#L101

**Comment by ILMTitan** [comment]
Done
