### ISSUE TITLE
After setting ACL, Find-GCSObject no longer shows ACL values 

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#180]

**Comment by chrsmith** [comment]
For future bug reports, copying and pasting the cmdlet output would be very useful.

However, I know exactly what the underlying problem is. There is an unfortunate default in the GCS APIs that I recently fixed in b6dae35198e, but there was a LIST call I missed.

**Comment by chrsmith** [comment]
Fixed with PR #183.
