### ISSUE TITLE
Need progress indicator for long running operations [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#181]
If operation will take more than 1s, show some kind of progress indicator, such as for:
Uploading files
Spinning up new VMs
Attaching disks
...

**Comment by ILMTitan** [comment]
There is a way to write to a progress bar, but for most of those things, there is no feedback on how progress is proceeding.

**Comment by chrsmith** [comment]
Yes, Jim is correct. The GCE API only returns an "operation" object that lets us know if it has failed, completed, or is still in-progress.

For operations where we do know progress -- IIRC file uploads or bulk-copying GCS objects -- we can use the built-in PowerShell progress indication.

@ILMTitan , taking a closer look it appears we only do this for `Remove-GcsObject` ([here](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/4c7758e204dd2da32f7cade51820eed0bef519b8/Google.PowerShell/Storage/GcsBucket.cs#L288)). Does it make sense to also apply a progress bar when you pipe multiple objects to `New-GcsObject` too? Are there other cmdlets where we should wire in a progress bar?

**Comment by ILMTitan** [comment]
One thing I am thinking about is having a progress bar that moves forward,
and resets to zero at some point, just to show we haven't hung.

**Comment by chrsmith** [comment]
Jim, did you look into this? Are there some specific cmdlets we should wire progress into? Or just the infinite spinner?

**Comment by YnR** [comment]
Seems like there is a progress bar that is often used in powershell, the yellow-on-teal bar that appears at the top. Could we use that?

**Comment by ILMTitan** [comment]
Closed in #213.
