### ISSUE TITLE
Gcs - Invalid tags for parameter descriptions

### ISSUE THREAD

**Issue by emdat** [GoogleCloudPlatform/google-cloud-powershell#201]
In some of the Gcs cmdlets, the parameter descriptions are introduced with a tag saying `<para typedef="description">`, which prevents the description from being parsed properly. It should work if you just make it `<para type="description"> </para>`.

**Comment by chrsmith** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-powershell/search?utf8=%E2%9C%93&q=typedef

**Comment by chrsmith** [comment]
Should be fixed now.
