### ISSUE TITLE
Gce - Invalid tags for parameter descriptions

### ISSUE THREAD

**Issue by emdat** [GoogleCloudPlatform/google-cloud-powershell#202]
In some of the Gce cmdlets, the parameter descriptions have the tags `<paratype="description"> </paratype>`, which prevents the description from being parsed properly. It should work if you just make it `<para type="description"> </para>`.

**Comment by chrsmith** [comment]
Is this still an issue, GitHub search doesn't show anything:
https://github.com/GoogleCloudPlatform/google-cloud-powershell/search?utf8=%E2%9C%93&q=paratype

**Comment by ILMTitan** [comment]
I am not sure exactly which PR I fixed this in, but I do recall fixing it.
