### ISSUE TITLE
Provide list or examples of acceptable values for parameters [userstudy] 

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#224]
When possible, put the information in the cmdlet reference, otherwise link to the appropriate documentation page for more description 

Common issues:
Machine types
Zones
ACL

**Comment by chrsmith** [comment]
We did a push on adding cmdlet examples, links, etc. e.g. https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/c92a451013de4a100c7323442d6ff650c68b1ef2/Google.PowerShell/Storage/GcsBucketWebsite.cs#L23
