### ISSUE TITLE
Implementing a Find-GCEInstance to match the GCS model [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#235]
alternatively, explicitly state that it can return one or many instances in the cmdlet description.

**Comment by ILMTitan** [comment]
@YNR I have already updated the docs to talk about getting all instances of a project or zone.

**Comment by ILMTitan** [comment]
I don't think this was a large enough issue that we should write a new cmdlet for. Users tended to get to Get-GceInstance.
