### ISSUE TITLE
Support different zones for disk and vm. [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#237]
it is currently possible using Objects, but it is unclear when setting the a zone parameter, if it applies to the disk zone or the vm zone.

**Comment by ILMTitan** [comment]
It is currently possible to specify different zones using objects, but the api throws an error: 
Invalid value for field 'resource.source': 'https://www.googleapis.com/compute/v1/projects/gcloud-powershell-testing/zones/asia-east1-a/disks/disk-1'. Disk must be in the same zone as the instance. [400]
