### ISSUE TITLE
Documentation: Organize commands in the reference alphabetically [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#240]

**Comment by chrsmith** [comment]
I believe this has been fixed for a long while. Please reactivate if I am missing something:

e.g.:
- http://googlecloudplatform.github.io/google-cloud-powershell/#/
- http://googlecloudplatform.github.io/google-cloud-powershell/#/google-compute-engine
- http://googlecloudplatform.github.io/google-cloud-powershell/#/google-compute-engine/GceImage
