### ISSUE TITLE
Consider explaining the values the API returns somewhere [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#243]
From the study:

> "in AWS, TERMINATED means it's unrecoverable. This [cmdlet reference] does not describe the states for outputs. I would search around until I find the what that means. Probably comes from API call, not cmdlet." -P5

**Comment by ILMTitan** [comment]
I feel like the instance resource is too large to describe in the description of the cmdlet. I am adding a link to the api resource description.

RELATED LINKS
    [Instance resource definition] (https://cloud.google.com/compute/docs/reference/latest/instances#resource)
