### ISSUE TITLE
Get-GCEImage with no param returns an error 

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#245]
Trying to use Get-GCEImage from the latest public build, and if no parameter is passed, it returns a cryptic error:
`Get-GceImage : Errors occured for multiple projects`

**Comment by chrsmith** [comment]
@ILMTitan I assume we should fix this, right? I assume more than one image request is failing, and we are just surfacing that in the cmdlet? We just need to do some basic parameter validation, right?

@YnR Does that make sense? Or did you close the issue for some other reason?

**Comment by ILMTitan** [comment]
@chrsmith Yann thought that having no parameters was causing this error, but in fact he was having an authentication problem. The information about each error exists to be drilled into. The only thing I can think of that would improve the top error message would be to append the message of one of the errors.
