### ISSUE TITLE
Authorizing with a .json file on a GCE instance doesn't work.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-powershell#249]
I think this is related to https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/68

After I gcloud auth, I still see auth errors when running on a GCE instance:
Activated service account credentials for: [jenkins-test@getting-started-dotnet.iam.gserviceaccount.com]

 [-] copies one file to an existing directory. 69ms
   GoogleApiException: Google.Apis.Requests.RequestError
   Invalid Credentials [401]
   Errors [
        Message[Invalid Credentials] Location[Authorization - header] Reason[authError] Domain[global]
   ]
   at Clear-GcsTestDir, C:\Users\root\workspace\dotnet-docs-samples\storage\powershell\Pester.Tests.ps1: line 24
   at <ScriptBlock>, C:\Users\root\workspace\dotnet-docs-samples\storage\powershell\Pester.Tests.ps1: line 150
   at Invoke-Blocks, C:\Users\root\AppData\Local\Temp\2\PesterRepo\1575736885\Pester\Functions\SetupTeardown.ps1: line 1
34
   at Invoke-TestCaseSetupBlocks, C:\Users\root\AppData\Local\Temp\2\PesterRepo\1575736885\Pester\Functions\SetupTeardow
n.ps1: line 92

**Comment by chrsmith** [comment]
After you run `gcloud auth`, I assume `gsutil` and `gcloud` work as expected?

For the PowerShell cmdlets we just use the usable auth, which has a specific order of how it gets your credentials. (IIRC it checks an environment variable first, and then it goes to the stored gcloud SDK creds.)
