### ISSUE TITLE
Support custom ACLs in GCS

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#259]
Support custom ACLs in GCS. We only support predefined ACLs, but not things like allowing a gmail user, etc.

**Comment by quoctruong** [comment]
@chrsmith, is this related to https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/234?

**Comment by chrsmith** [comment]
Yes, those are the same bug. I looked into this a while back, and the problem was how to specify all the distinct types of ACLs. It was unclear from looking at the API how to format a request to specify all of the unique types of ACLs listed on:
https://cloud.google.com/storage/docs/access-control/

Why don't you take a stab at it and if you run into a similar roadblock let me know, and I can try to get you in touch with the right people on the GCS API side.

**Comment by quoctruong** [comment]
This is now supported with #368.
