### ISSUE TITLE
Problems with Google Cloud DNS docs

### ISSUE THREAD

**Issue by dupuy** [GoogleCloudPlatform/google-cloud-powershell#280]
PR#279 adds Google Cloud DNS to the left navbar on the Reference tab, but the Cmdlets tab for Google Cloud DNS (http://googlecloudplatform.github.io/google-cloud-powershell/cmdlets/google-cloud-dns.html) gets a 404 (in contrast to [Google Cloud SQL](http://googlecloudplatform.github.io/google-cloud-powershell/cmdlets/google-cloud-sql.html)).

**Comment by chrsmith** [comment]
@emdat @ILMTitan I presume we just need to regenerate `cmdlets.json` and republish the website?

**Comment by ILMTitan** [comment]
I believe that is correct.

**Comment by ILMTitan** [comment]
Turns out, Google Cloud DNS needed to be added as a product in two places. The website is fixed, and the related PR fixes the generating data.

**Comment by ILMTitan** [comment]
PR #279 Closes this issue.
