### ISSUE TITLE
The application name should be a valid User-Agent token.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-powershell#286]
In [this line](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/0cc9671bbf4ac45f230dd95329a9407d305bb8c2/Google.PowerShell/Common/GcloudCmdlet.cs#L68) the application name is specified as `"Google Cloud Powershell"`, the value of the `ApplicationName` should actually be a valid `User-Agent` token, that is, no spaces. I would recommend the same name as the repo, `"google-cloud-powershell` as the value for it.

Without the change all that the analytics table will contain is the value `"Google"` which is not very useful.

**Comment by chrsmith** [comment]
@ILMTitan IIRC I saw a PR fly by that addressed this. Is this fixed? Or is there more work to do? Also, thanks for reporting this @ivannaranjo !

**Comment by ILMTitan** [comment]
PR #287 has not yet been merged. From what I understand, that is all we have to do.
