### ISSUE TITLE
Specify metadata when creating/writing an object

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-powershell#29]
It would be nice to be able to pass key/value pairs for metadata when using New-GcsObject or Write-GcsObject.

Use case: I have a file which is about 1MB long and used for validating that time zone data has been parsed correctly. It includes a hash of its distinguishing content. Code validating local parsing could fetch just the metadata for the object, and only download the whole file (in another request) if the hash isn't as expected. Note that the hash is only the hash of part of the file (after some headers) so this has to be done via object metadata rather than the standard headers.

**Comment by chrsmith** [comment]
Evidently I added this a while ago but never updated the bug. Sorry.

Integration tests:
https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/1e61ddd78adf75162708db329c10b70dd8a11eb3/Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1#L196

https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/1e61ddd78adf75162708db329c10b70dd8a11eb3/Google.PowerShell.IntegrationTests/Storage/Storage.GcsObject.Tests.ps1#L745
