### ISSUE TITLE
Add website documentation for PowerShell Cmdlet Provider.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-powershell#312]
The code for the provider is in, but there is not yet any documentation for it.

**Comment by chrsmith** [comment]
When updating the cmdlet reference website, the best place for mentioning the provider would be here:
https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/master/website/js/app/controllers/content-product.ng#L82

**Comment by quoctruong** [comment]
The doc is now available at https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/380
