### ISSUE TITLE
PSModulePath is not set up properly

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#314]
Today the GoogleCloudPowerShell module gets installed into "${env:ProgramFilesx86}\Google\Cloud SDK\google-cloud-sdk\platform", and the installer adds the path to the GoogleCloudPowerShell folder to $env:PSModulePath.

This setup prevents the module from being loaded using Import-Module GoogleCloudPowerShell. You can load it using the full path to the module folder or using the full path to the psd1 file it contains, but you can't load it with Import-Module. This setup also prevents Get-Command -Module GoogleCloudPowerShell from working. Generally, anything that is dependent on lookup by module name (dependencies taken by other modules, for example) will not work.

To fix this, $env:PSModulePath should contain the folder _above_ the GoogleCloudPowerShell folder rather than the GoogleCloudPowerShell folder itself. Personally I recommend creating a PowerShell folder at the same level as GoogleCloudPowerShell, moving the GoogleCloudPowerShell folder into the PowerShell folder, and setting up the PowerShell folder you create as the item that you add to $env:PSModulePath.  That is the best solution to this issue, keeping PSModulePath folders clean and PowerShell focused so that you don't impact PowerShell performance, and setting your module up to be discoverable by name properly.

**Comment by ILMTitan** [comment]
Thank you for catching this.

**Comment by chrsmith** [comment]
See #315 when we get to fixing this.

**Comment by chrsmith** [comment]
@KirkMunro thanks for reporting this and other PowerShell issues. This has been fixed in the repo. It will be live in the next release of the Cloud SDK, in the next week or two. (The next time you `gcloud components update`.)
