### ISSUE TITLE
The "PowerShell" suffix in your "GoogleCloudPowerShell" module name is 100% redundant

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#315]
You don't see people tacking "Python" and "Ruby" on the end of all of their package/gem names, do you?

Since this is beta (I think it's just beta), please consider dropping the "PowerShell" suffix from the folder name and the psd1 file, and updating references accordingly. You'll save scripters who use your platform a lot of unnecessary typing in the long run.

**Comment by chrsmith** [comment]
Good point. There also was a name change half way through our development, from "Google Cloud PowerShell" to "Google Cloud Tools for PowerShell". So there are a few places here and there that still reflect the old name.

**Comment by chrsmith** [comment]
@KirkMunro thanks for reporting this and other PowerShell issues. This has been fixed in the repo. It will be live in the next release of the Cloud SDK, in the next week or two.
