### ISSUE TITLE
Replace the *'s in your psd1 file with an array of actual export names

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#316]
It's a known issue in PowerShell that using '*' in Export* fields in a manifest negatively impacts performance.

Best practices dictate actually listing all exports in a list, and if you don't like doing it manually, keep it current with a script.

**Comment by ILMTitan** [comment]
Kirk, thank you for your comments.
Do you mean "using '\*' in Export\* fields"? I think the asterisks got eaten by the markdown.

**Comment by vors** [comment]
Kirk is right.
For the details about associated cost and benchmarking see this PR in azure-powershell
https://github.com/Azure/azure-powershell/pull/1763#issuecomment-185009796

**Comment by KirkMunro** [comment]
@ILMTitan Yeah, thanks for catching that, I was trying to log a bunch of issues before supper and didn't take the time to make sure I escaped the asterisks.

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/369
