### ISSUE TITLE
Move your binary module from NestedModules to RootModule

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#317]
You're using a manifest to describe your binary module, but you're not properly making the association between the manifest and the binary module it describes. A better practice is to put the relative path to the DLL (without the leading .\ which is unnecessary) in the RootModule field of the manifest, and save NestedModules for _other_ modules that you want to nest in this module.

**Comment by chrsmith** [comment]
We could fix this when we get around to #316 . Note however we'd need to make the changes to both PowerShell modules.

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/369
