### ISSUE TITLE
Inconsistent "return a collection of thingies" in GCS cmdlets

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#331]
Get-GcsBucket returns a collection of buckets
Get-GcsObject returns a single object
Find-GcsObjects return a collection of objects

What's the preferred PS verb and pluralization for "get a collection" and can we use that consistently?

**Comment by quoctruong** [comment]
The PowerShell convention is to not use plural noun in the cmdlet so we should change Find-GcsObjects to Find-GcsObject.

**Comment by chrsmith** [comment]
Yes, PowerShell avoids plurals. e.g. `dir` and `ls` maps `Get-ChildItem` not `Get-ChildItems`.

`Get-GcsBucket` returns a sequence of buckets.
`Get-GcsBucket -Name $name` returns a single bucket.

I believe we are consistent in our cmdlets in this regard, e.g. we have `Find-GcsObject` (not `-Objects`) ([link](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/4cc2dddca31efe1b6aeea5df6626faf52368c6cf/Google.PowerShell/Storage/GcsObject.cs#L562))

**Comment by quoctruong** [comment]
We should merge Get-GcsObject and Find-GcsObject to be consistent with Get-GcsBucket. This is also consistent with built-in cmdlet like Get-ChildItem.

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/377#pullrequestreview-8511027
