### ISSUE TITLE
Incorrect behavior when gcloud has two accounts

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#334]
When gcloud has two different accounts available, it appears that the active gcloud config account is NOT being used by PowerShell. This should "just work" because of the we are using the Application Default Credentials when initializing the Google API client libraries.

However, this is the behavior I am seeing:

````
PS C:\src\github.com\chrsmith\google-cloud-powershell\Google.PowerShell\bin\Debug> gcloud auth list
Credentialed Accounts:
 - chrsmith@google.com ACTIVE
 - chrsmithdemos@gmail.com
To set the active account, run:
    $ gcloud config set account `ACCOUNT`
````

The active account is my @google.com one, so it should have access to `gcloud-powershell-testing`. However, that doesn't appear to be the case. (The extra text "Handler was created" and "Abnormal response" is from hooking up an ILogger to the client libraries.)

````
PS C:\src\github.com\chrsmith\google-cloud-powershell\Google.PowerShell\bin\Debug> Get-GcsBucket -Project gcloud-powershell-testing
Handler was created. SupportsRedirectConfiguration=True, SupportsAutomaticDecompression=True
Add parameter should not get null values. type=Query, name=key
An abnormal response wasn't handled. Status code is Forbidden
Abnormal response is being returned. Status Code is Forbidden
Get-GcsBucket : Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
    Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]
At line:1 char:1
+ Get-GcsBucket -Project gcloud-powershell-testing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-GcsBucket], GoogleApiException
    + FullyQualifiedErrorId : Google.GoogleApiException,Google.PowerShell.CloudStorage.GetGcsBucketCmdlet
````

However, if I use the Cloud Storage provider, I get the list of accounts for all of the projects associated with my @gmail.com account.

````
PS C:\src\github.com\chrsmith\google-cloud-powershell\Google.PowerShell\bin\Debug> dir gs:\ | select Name

Name
----
blog-posts
chrsmith-demos.appspot.com
chrsmith-pictures
database-snapshots-prod
shopbot9000
staging.chrsmith-demos.appspot.com
us.artifacts.chrsmith-demos.appspot.com
vm-config.chrsmith-demos.appspot.com
vm-containers.chrsmith-demos.appspot.com
````

**Comment by chrsmith** [comment]
@ILMTitan @quoctruong This is definitely GA blocking, could either of you try to repro this and investigate this week?

**Comment by chrsmith** [comment]
Note that changing the current gcloud config doesn't alter this behavior. For cmdlets, since we recreate the credential initialize for each cmdlet, we should pick up this change. (Not sure about the GCS provider, might be a bug there.)

However, changing the current gcloud account doesn't appear to change the behavior of our cmdlets:

````
PS C:\src\github.com\chrsmith\google-cloud-powershell\Google.PowerShell\bin\Debug> gcloud config set account chrsmith@google.com
Updated property [core/account].
PS C:\src\github.com\chrsmith\google-cloud-powershell\Google.PowerShell\bin\Debug> dir gs:\ | select Name

Name
----
< list of buckets that @gmail.com has access to, not the @google.com account >
````

**Comment by quoctruong** [comment]
I can do this on Wednesday.

**Comment by chrsmith** [comment]
NOTE: See internal thread with the Cloud SDK folk. Perhaps we were abusing `gcloud config set account` and should have instead been using `gcloud auth application-default login`. It might be possible that it is possible to have a _different_ [application default credentials](https://developers.google.com/identity/protocols/application-default-credentials) (ADC) than the current user the Cloud SDK is logged in as. If that is the case, we probably need to do more checking before we rely on ADC, since that is the reason why you get the confusing behavior I reported.

**Comment by quoctruong** [comment]
Fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/349.
