### ISSUE TITLE
Set-Content silently fails

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#338]
The following command completes successfully, though I would have expected an error that Bucket "folder" does not exist. The error case here is where the user forgets to specify the bucket.

````
Set-Content gs:\folder\file.txt -Value "Hello, Cloud Storage!"
````

**Comment by ILMTitan** [comment]
This command actually creates a new object, which is consistant with how Set-Content works with the local filesystem. The actual bug here is that it does not refresh the local object cache when a new object is created, making it look like nothing happened at all.
