### ISSUE TITLE
dir is too slow

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#339]
CD into a GCS bucket/folder that has more than 500 objects. Type `dir -Recurse`.

Expected: It takes a while, sure.

Observed: After a minute or so I gave up.

**Comment by ILMTitan** [comment]
I just tried this on the doublehelixbackup bucket, and while it was slow, it was displaying the objects as they were returned from the server. Can you point me to bucket where this fails as you describe?

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/468 and https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/391.
