### ISSUE TITLE
Write-GcsObject inconsistencies

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#340]
Problems with `Write-GcsObject`.

There is no parameter set that takes an existing GcsObject, so it doesn't pipeline well with Get-GcsObject or the Provider.

It's `Contents` parameter should just be `Value`, to be idiomatic.

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/346
