### ISSUE TITLE
Add provider documentation to the Quickstart.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-powershell#342]
The [quickstart](https://www.google.com/url?q=https://cloud.google.com/tools/powershell/docs/quickstart&sa=D&ust=1476143091992000&usg=AFQjCNFLE2vnk-PKeORNWtEickpwSPUMSQ) would be a good place to give a very brief introduction to the Google Cloud Storage provider.

**Comment by quoctruong** [comment]
This is now done.
