### ISSUE TITLE
Fix Pester Tests

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-powershell#345]
Pester tests for the following cmdlets are failing:
Get-GceBackendService
Get-GceDisk
Compute.GceFirewall.Tests.ps1 (script level error)
Import-GcSqlInstance
Update-GcSqlInstance

**Comment by chrsmith** [comment]
@ILMTitan Leave the `GcSqlInstance` cmdlets to me. (And if you don't hear back from me in a while, please be ruthless in bugging me.)

**Comment by ivannaranjo** [comment]
Ping? Was this done?

**Comment by quoctruong** [comment]
@ivannaranjo We fixed some tests and remove the flaky tests.
