### ISSUE TITLE
GCE cmdlets don't support Subnet or PrivateNetworkIP parameters

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#351]
From an internal request:

We created a Powershell script to automatically setup a SQL Server cluster. Most of the script uses the Cloud PowerShell CmdLets except for cases where the existing CmdLet did not provide the same functionality as the "gcloud" command. In those cases we had to use PowerShell to call the "gcloud.exe" command. It will make the process better to have those those parameters.

For your reference, below is the "gcloud" command that we use:
`gcloud.exe compute instances create $node1 --machine-type $machine_type --zone $zone --subnet $subnet1_name 
    --private-network-ip=$ip_node1 --can-ip-forward --disk="name=$node1,boot=yes,auto-delete=yes" --quiet 
    --metadata windows-startup-script-cmd="netsh interface ip set address name=Ethernet static addr=$ip_node1 mask=255.255.0.0 gateway=$subnet1.0.1 gwmetric=1"`

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/456.
