### ISSUE TITLE
Support Coldline storage from GCS cmdlets

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#355]
Cloud Storage just announced a new tier of storage "COLDLINE" for even longer-term duration. I think we just need to update the enum/validation set we use for the field in New-GcsBucket. But updating an existing test to tweak the setting wouldn't hurt either.

https://cloudplatform.googleblog.com/2016/10/introducing-Coldline-and-a-unified-platform-for-data-storage.html

**Comment by quoctruong** [comment]
The storage is now supported with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/365.
