### ISSUE TITLE
Minor CSS issues on cmdlet reference doc website

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#358]
- Cmdlet parameters table should fill 100% of the width of the content container. Instead, only grows up to the size of the longest parameter description. e.g. [Start-GceInstance](http://googlecloudplatform.github.io/google-cloud-powershell/#/google-compute-engine/GceInstance/Start-GceInstance).
- Fonts (Robot, Roboto Mono) are not rendered when viewing the site under mobile Safari. Perhaps we need to set a fallback font for the font names? Perhaps the way we load those fonts isn't supported on Safari?

**Comment by chrsmith** [comment]
Some other notes:

- Clicking outside of a parameter set (but not on another) should deselect the parameter set.
- Don't sort the parameters when a parameter set is selected. (Just have them greyed out in place.)
- Click on the parmeter name in the parameter set widget to go to the parameter.
- Resource page needs the parent project context. e.g. "Cloud Storage > GcsBucket".

**Comment by quoctruong** [comment]
@chrsmith, if I click on a noun (for example, GcsBucket in Google Cloud Storage), then the list on the left side will show me the cmdlets associated with this now. However, if I click on another noun (e.g. GcsObject), then it will automatically close the list associated with the previous noun. I feel that the previous list should not be close unless the user explicitly chooses to do so?

**Comment by ivannaranjo** [comment]
Ping? Was this done?

**Comment by quoctruong** [comment]
@ivannaranjo I spoked with Chris before and it was by design so closing this.
