### ISSUE TITLE
Can we add the GCS Provider to the Quickstart docs?

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#371]
Can we add coverage of the GCS Provider to [the Quickstart docs](https://cloud.google.com/tools/powershell/docs/quickstart)? I think we ask people to start the Cloud Tools for PowerShell shortcut from the start menu, show them some cool stuff, then mention that they can bring the GCS provider into any PS window via "Import-Module GoogleCloud".

**Comment by chrsmith** [comment]
@quoctruong I believe I saw a CL fly by that fixed this.

**Comment by quoctruong** [comment]
@chrsmith Yes, the CL is still in progress.

**Comment by quoctruong** [comment]
The provider is now in the Quickstart docs.
