### ISSUE TITLE
read-gcsobject error message ambiguous

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#372]
Can we make "Read-GcsObject : Not Found" to "Object Not Found" instead? Otherwise I was confused as to whether the Read-GcsObject command itself wasn't found or something else. In general, the error messages should mention what wasn't found, e.g. "Bucket Not Found", "Object Not Found", etc.

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/376. The error message will now be "Storage object 'blah' does not exist."
