### ISSUE TITLE
You're still using wildcards in ToExport fields in GoogleCloud.psd1

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#399]
Related to #316 (which is now closed), the latest release uses wildcards for FunctionsToExport, AliasesToExport, and VariablesToExport in GoogleCloud.psd1. This will impact performance in PowerShell. You should simply set these values to @() so that they are defined as exporting nothing.

Note: _do not_ simply remove them or comment them out, as that will have a negative impact as well -- simply set them to @() in every psd1 file that you have when you are not exporting that type of object to PowerShell.

To verify you have this issue properly addressed, the following command should not return anything at all:
```
gmo -li GoogleCloud | select -expand ModuleBase | gci -r -fi *.psd1 | select-string '^(#+\s*[a-z]+ToExport|\s*[a-z]+ToExport\s*=\s*''\*'')'
```

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/409. It should be available later this week with the release of the new Google Cloud SDK.
