### ISSUE TITLE
Get-GcsBucket : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#404]
I assume that if none of my projects have any buckets, that it causes this problem:

PS C:\Users\csells> Get-GcsBucket
Get-GcsBucket : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-GcsBucket
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-GcsBucket], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Google.PowerShell.CloudStorage.GetGcsBucketCmdlet

**Comment by quoctruong** [comment]
This is now fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/413
