### ISSUE TITLE
need to specify bucket and object names explicitly when I'm using the GCS provider

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#406]
I think I should be able to just do:

cd gcs:\csells-bucket1
new-gcsobject foo.txt -value foo

instead I have to do:

cd gcs:\csells-bucket1
new-gcsobject -bucket csells-bucket1 -objectname foo.txt -value foo

This need to be explicit seems to defeat the purpose of having a provider in the first place.

**Comment by quoctruong** [comment]
Hi @csells, you have to use "Set-Content foo.txt -Value foo" instead of New-GcsObject. The provider adds support for Set-Content and not New-GcsObject.

**Comment by csells** [comment]
Why wouldn't the provider provide context for all of the GCS cmdlets? Why would it work for Set-Content but not New-GcsObject?

**Comment by quoctruong** [comment]
@csells, if you look at the section provider cmdlets at https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Providers, you can see that by implementing the providers, we are implementing support for the built-in PowerShell cmdlets (Set-Content is among them), not the GCloud cmdlet.

If you want the New-GcsObject foo.txt -Value foo behavior though, what we can do is interpreting foo.txt as a GCS Provider path. This should add a work-around for this.

**Comment by quoctruong** [comment]
This is now fixed in the latest module. Now you can run command like "New-GcsObject -ObjectName foo.txt -Value foo" inside the provider.
