### ISSUE TITLE
Set-GcsObject -PredefinedAcl PublicRead removes project permissions

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#424]
The docs for "publicRead" say that the project owner gets OWNER access, and allUsers get READER access. However, what actually happens is that all users get read access and all of the project permissions are completely dropped. For example, if I do the following:

`PS gs:\csells-psfun1\images\> ls | %{ Set-GcsObject $_ -PredefinedAcl PublicRead }`

and then write this program:

```// grab a random image
var client = StorageClient.Create();
var images = client
  .ListObjects("csells-psfun1", "images/", new ListObjectsOptions { Projection = Projection.Full })
  .Where(i => i.Acl.Any(acl => acl.Entity == "allUsers"))
  .ToArray();
ViewBag.Url = images[(new Random()).Next(0, images.Length)].MediaLink;
```

then it works great when running from my local laptop, but it doesn't work at all well when running from a deployed ASP.NET app (the program crashes until that object is removed from the bucket).

I would expect setting publicRead would mimic the "Public link" checkbox in the GCS Browser.

**Comment by quoctruong** [comment]
Hi @csells, from the documentation [here](https://cloud.google.com/storage/docs/access-control/lists#predefined-acl), it seems setting publicRead actually removes project permissions so I think the cmdlet is doing what it is supposed to do. We can add more documentation or a warning message to the user when using this setting?

**Comment by quoctruong** [comment]
We added documentation that all other project permissions are dropped in the doc http://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage/GcsObject/Set-GcsObject
