### ISSUE TITLE
Set-GcsObject docs do not enumerate the meanings of the PredefinedAcl enum

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-powershell#425]
https://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage/GcsObject/Set-GcsObject

publicRead is briefly mentioned ("the project owner gets OWNER access, and allUsers get READER access"), but none of the other enum values are doc'd at all.

**Comment by quoctruong** [comment]
The doc is now updated http://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage/GcsObject/Set-GcsObject
