### ISSUE TITLE
Add unit test to confirm envvar overwrite of Cloud SDK settings

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#430]
There are many ways to set the current project in the Cloud SDK. One way is to set an environment variable. We should add a unit test to confirm that our method of shelling out to the Cloud SDK to gather configuration data picks up on settings specified via environment variable.

**Comment by quoctruong** [comment]
Test is now added with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/431.
