### ISSUE TITLE
Cross-Platform bits not working on OS X

### ISSUE THREAD

**Issue by quoctruong** [GoogleCloudPlatform/google-cloud-powershell#438]
We get an error like this:

get-gcsbucket : One or more errors occurred. (Could not find file 
'/Users/quoct/.config/gcloud/config_sentinel'.)
At line:1 char:1
+ get-gcsbucket
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], AggregateException
    + FullyQualifiedErrorId : System.AggregateException

This is most likely because the GetLastWriteTime throws a FileNotFoundException in OS X but not in Windows when the file does not exist.

**Comment by chrsmith** [comment]
While we should handle this edge case, we should also log a bug on the .NET
Core project if this is an inconsistency in the .NET APIs.

**Comment by quoctruong** [comment]
This issue is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/440. I've opened a bug on the .NET repo at https://github.com/dotnet/corefx/issues/15633. However, it seems that they intentionally wanted to throw on Linux (see https://github.com/dotnet/corefx/issues/1728)
