### ISSUE TITLE
Request: `gcloud components install powershell` on Linux and macOS

### ISSUE THREAD

**Issue by AkihiroSuda** [GoogleCloudPlatform/google-cloud-powershell#439]
Now powershell officially supports Linux and macOS.

So could you please consider enabling `gcloud components install powershell` on Linux and macOS as well?

**Comment by chrsmith** [comment]
Yes, this is definitely on our radar.

We have been doing some work and testing to confirm that our cmdlets work on Linux and macOS. However we are holding off on integrating the cross-platform PowerShell runtime into the Cloud SDK until it reaches beta quality. Currently the cross-platform PowerShell is in Alpha and had some quality issues.

If in a few months the PowerShell bits for other platforms is in better shape, but still doesn't have a "beta" or "GA" label we can revisit this.

**Comment by adarobin** [comment]
Any news on this?  PowerShell 6.0 is in Beta now.

**Comment by quoctruong** [comment]
@adarobin, we plan to release the beta version of the cross-platform cmdlets to the PowerShell gallery in this quarter.

**Comment by ivannaranjo** [comment]
Ping? Was this done?

**Comment by beatcracker** [comment]
PowerShell Core reached GA state: [PowerShell Core 6.0: Generally Available (GA) and Supported!](https://devblogs.microsoft.com/powershell/powershell-core-6-0-generally-available-ga-and-supported/)

Can we have cross-platform cmdlets now, pretty please?

**Comment by quoctruong** [comment]
@beatcracker, the module should work cross-platform already. Have you given it a try?

**Comment by beatcracker** [comment]
@quoctruong Nope, because I had no idea - it's not mentioned anywhere and this issue is still open. This is awesome news, thank you!

**Comment by beatcracker** [comment]
It's alive!

![ps-linux-blur](https://user-images.githubusercontent.com/7583050/55011941-b85b0500-4ff7-11e9-928b-e11189eab687.PNG)
