### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by ahandley** [GoogleCloudPlatform/google-cloud-powershell#444]
In Google.PowerShell/PubSub/GcpsMessage.cs, the first and fourth code examples are the same, but their descriptions are different:

<code>PS C:\> Get-GcpsMessage -Subscription "my-subscription"</code>
    ///   <para>This command pulls down one or more messages from the subscription "my-subscription" in the default project.</para>

<code>PS C:\> Get-GcpsMessage -Subscription "my-subscription"</code>
    ///   <para>
    ///   This command pulls down one or more messages from the subscription "my-subscription" in the default project
    ///   and sends an acknowledgement for each message.
    ///   </para>

**Comment by quoctruong** [comment]
This is now updated with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/443.
