### ISSUE TITLE
GceManagedInstanceGroups does not handle region managed instance groups.

### ISSUE THREAD

**Issue by ILMTitan** [GoogleCloudPlatform/google-cloud-powershell#484]
Regional managed instance groups did not exists when we wrote the GceManagedInstanceGroups cmdlets.
Therefore, some operations, such as `Get-GceManagedInstanceGroup | Remove-GceManagedInstanceGroup` (including our tests) will failed if there is a region managed instance group.

**Comment by quoctruong** [comment]
This is now fixed in the latest module.
