### ISSUE TITLE
Remote powershell on GCE VM

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-powershell#499]
Is there an easy/secure solution for executing remote powershell commands to GCE VM machines?

To be more specific:  how to enable powershell is documented by Microsoft already.   The ask here is about a "secure" , easy to follow solution.   
Including (1) install necessary components  (2) opening IP ports (I would do it on internal IP only by default),  add firewall rule  (3) Add a authentication/authorization control.

**Comment by Deren-Liao** [comment]
This idea was inspired by that: 
I wanted to turn on/off Stackdriver logging by running a command or something without have to logging on the machine.

**Comment by ILMTitan** [comment]
Yes, WinRM allows you to execute PowerShell commands on remote computers. I quickly found on article on how [here](https://www.howtogeek.com/117192/how-to-run-powershell-commands-on-remote-computers/). The `Enable-PSRemoting` should not be needed, as GCE Windows VMs have WinRM enabled by default.

**Comment by chrsmith** [comment]
Closing this out as WAI. Please reactivate if there is something we should do here, but looking at that blog post and what Jim said about having WinRM enabled by default, things should "just work".
