### ISSUE TITLE
Apis.Core version 1.20.0.0 Downgrade

### ISSUE THREAD

**Issue by ahandley** [GoogleCloudPlatform/google-cloud-powershell#521]
The BigQuery branch relies on Google.Cloud.BigQuery and Google.Apis.Bigquery, among others.  To use the beta version 9 of Cloud.BigQuery, version 1.20.0.0 is needed for all of the Google.Apis packges.  To use beta 10 of Cloud.BigQuery, version 1.24 + is needed.  Upgrading to the recent versions 1.24+ caused a number of dependency issues, so I downgraded all of the packages to versions 1.20 to push stable code.  This needs to be further investigated.

**Comment by quoctruong** [comment]
This is done with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/563
