### ISSUE TITLE
Poor experience installing GoogleCloud module from the PSGallery

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#534]
I installed the GoogleCloud PowerShell module from the PSGallery and ran into a few issues we should smooth out. Given the various ways each of these could be addressed, it might warrant an in-person discussion.

To reproduce, type `Install-Module GoogleCloud` into an admin PowerShell window. (On a machine without the Cloud SDK installed?)

Window output:

````
PS C:\WINDOWS\system32> get-gcsbucket
Google Cloud SDK is not found in PATH. The SDK is required to run the module.
 
Installing Google Cloud SDK
Do you want to install Google Cloud SDK? If you want to force the installation without prompt, set $env:GCLOUD_SDK_INSTALLATION_NO_PROMPT to true.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
 
Y
 
WARNING: You may have to restart the shell before gcloud can be used.
WARNING: Please also make sure to run 'gcloud init' before using the module.
get-gcsbucket : Command gcloud config config-helper --force-auth-refresh --format=json failed with error: 'gcloud' is not recognized as an internal or external command,
operable program or batch file.
At line:1 char:1
+ get-gcsbucket
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException
````

**Issue #1 (P3)**

After I type "Y" to install the Cloud SDK, I see the bytes being written as the file is download, but no progress bar. Is it possible to show a progress bar instead, as the number of bytes isn't actually useful?

**Issue #2 (P3)**

Notice how after the Cloud SDK is supposedly installed, PowerShell invokes the cmdlet which fails because `gcloud` is not found on the path. As it turns out the text "you may have to restart the shell" is incorrect.

You _will_ need to restart the shell in order to pick up on the env variable changes. So we should either update the text or do Env Var schenanigans to make sure it is up to date.

**Issue #3 (P1)**

The Cloud SDK isn't actually installed automatically. When you type "Y", the Cloud SDK is downloaded and _started_. But you need to manually click through the installer UI. This definitely isn't what I expected.

At the very least we should block until the installer process exits, e.g. "Launching Cloud SDK installer UI. Blocking until installation is complete [pid XXX]". However, it seems much more convenient to just install it silently. (e.g. the behavior of GCLOUD_SDK_INSTALLATION_NO_PROMPT.)

I'm happy to accept a EULA or something. Just needing to click through the installer defeats the purpose of installing the PowerShell module entirely from the command-line.

**Comment by chrsmith** [comment]
One other random thought, if we do silently install the Cloud SDK we also need to prompt and run `gcloud init` so that the cmdlets will actually work.

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/538.
