### ISSUE TITLE
Do some SEO on our documentation site

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/google-cloud-powershell#546]
Use your favorite search engine and query for "Get-GCEImage". Our documentation is nowhere to be seen!

The canonical doc page should at least appear on the first page. Need to figure out what the problem is.
http://googlecloudplatform.github.io/google-cloud-powershell/#/google-compute-engine/GceImage/Get-GceImage

- Is the fact the docs are an Angular website, and we don't have the right text in the `<title>` element a problem?
- Is the domain GoogleCloudPlatform.githubpages.io penalized/blacklisted?
- Is it not crawlable? And we need a sitemap.xml file?

**Comment by chrsmith** [comment]
A search for "Copy-GcsObject site:googlecloudplatform.github.io" only returns the first page of our docs. So it probably is crawler-related. Though I thought Googlebot now executed JavaScript...

**Comment by ILMTitan** [comment]
I wonder if the problem is that every link is an anchor tag, meaning that the crawler thinks it will catch them by simply reading the whole front page. I bet that the crawler skips any part of a link after `#`, and so see all of our links as the same link.

**Comment by chrsmith** [comment]
Spent some time this morning learning more about Angular and how it relates to SEO and things. ([This talk](https://www.youtube.com/watch?v=JlP5rBynK3E) seemed interesting.)

Though, reviewing the metadata tags in `index.html`, having hard-coded `<title>` and `<description>` tags isn't helping. But I'd assume that hard-coding the `<canonical>` tag is what is the root problem. Since we are instructing web crawlers that the homepage is the canonical URL for every single piece of our docs.
