### ISSUE TITLE
Start-BqJob for Load type job does not allow specifying MaxBadRecords

### ISSUE THREAD

**Issue by jasper-smith** [GoogleCloudPlatform/google-cloud-powershell#550]
When submitting a new Load job via Start-BqJob I need to pass the MaxBadRecords value to the load job configuration in order for a load job to succeed when I know there are a number of malformed records in the source. I can do this via the bq tool but I would rather not shell out to that given that the poweshell cmdlet is almost exactly what I need.

**Comment by quoctruong** [comment]
@jasper-smith, thank you for the suggestion. We'll add a -MaxBadRecords parameter.

**Comment by quoctruong** [comment]
@jasper-smith, this parameter is now available in the new version of the module!
