### ISSUE TITLE
Missing cmdlets for views

### ISSUE THREAD

**Issue by a-vzhik** [GoogleCloudPlatform/google-cloud-powershell#556]
Hi 

It seems it's impossible to create/update BigQuery views with current version of PowerShell Tools. (If I'm wrong please give me a proper reference). I tried to bypass the problem with `bq` utility, but it doesn't support multiline query. It's possible to join a query into a single line, but in our project views are quite complex, with comments `--like this` and I'd like to have them well formatted in the storage).  

`Get-` and `Remove-` cmdlets for views are the same as for tables: `Get-BqTable` and `Remove-BqTable` respectively. But `New-` and `Set-` cmdlets require additional parameters 
- `New-BqView` requires `-Sql` and `-UseLegacySql`
- `Set-BqView`  requires `-Sql`

Implementation is quite straightforward:  
1. Missing properties are added to `New-BqTable` and `Set-BqTable`. 
2. `New-BqView` and `Set-BqView` are cloned from `New-BqTable` and `Set-BqTable` and missing properties are added. In this case for consistency it's reasonable to create view versions of  `Get-` and `Remove-` cmdlets (it could be simple inheritance).

**Comment by quoctruong** [comment]
@a-vzhik thanks for the suggestion @a-vzhik, I'll look into this.

**Comment by quoctruong** [comment]
@a-vzhik We're closing this issue for now because the module is in maintenance mode and we don't plan to release new cmdlets.
