### ISSUE TITLE
Find-GcsObject throws errors

### ISSUE THREAD

**Issue by Benny-Ayalew** [GoogleCloudPlatform/google-cloud-powershell#564]
The example at http://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage has an error in it.  specifically, the line below 

**Find**-GcsObject -Bucket $bucket
should instead read
**Get**-GcsObject -Bucket $bucket

There is no Find-GcsObject Cmdlet listed at the link below
http://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage/GcsObject

**Comment by ILMTitan** [comment]
Thank you for pointing this out.
The documentation has now been fixed.
