### ISSUE TITLE
Google Cloud Datastore Support

### ISSUE THREAD

**Issue by adarobin** [GoogleCloudPlatform/google-cloud-powershell#567]
Any plans to add cmdlets for Google Cloud Datastore?

**Comment by quoctruong** [comment]
@adarobin Thanks for the suggestion. We currently don't have any plans to add new cmdlets at the moment but we will revisit it if there's a strong need for those cmdlets.

**Comment by adarobin** [comment]
@quoctruong Would you consider pulling in Google.Cloud.Datastore.V1+ dependencies as a package so I don't have to hunt for dll's and their dependencies manually?

Currently, I'm doing something like this:
```
$DatastoreDLLPath = "/Users/adarobin/GoogleCloudDatastore/Google.Cloud.Datastore.V1.dll"
Add-Type -Path $DatastoreDLLPath

function Invoke-VCIQueryGCPCustomerDB {
    [cmdletbinding(DefaultParameterSetName="All")]
    Param(
        [parameter(ParameterSetName="byProjectId")] [string]$projectId,
        [parameter(ParameterSetName="byBillingId")] [string]$billingId
    )
    $dbProjectId = "a-project-id"
    $namespace = "a-namespace"
    $kind = "Project"

    $db = [Google.Cloud.Datastore.V1.DatastoreDb]::Create($dbProjectId, $namespace)
    $query = [Google.Cloud.Datastore.V1.Query]::new($kind)
    if ($PSCmdlet.ParameterSetName -eq "byProjectId") {
        $query.Filter = [Google.Cloud.Datastore.V1.Filter]::Equal("projectId", $projectId)
    }
    if ($PSCmdlet.ParameterSetName -eq "byBillingId") {
        $query.Filter = [Google.Cloud.Datastore.V1.Filter]::Equal("billingId", $billingId)
    }
    $results = $db.RunQuery($query)
    $results.Entities.Properties
}
```

**Comment by quoctruong** [comment]
@adarobin, is this needed for some interaction with the module?

**Comment by adarobin** [comment]
@quoctruong 

Not directly, I am using the module in some of my PowerShell scripts.  I also have the need to query data from Google Cloud Datastore in said scripts.

Since there are not any cmdlets for Google Cloud Datastore, I am loading the .Net SDK Module for Google Cloud Datastore into my script and directly using it's classes.  Unfortunately, this requires hunting down the DLLs and dependencies manually.

If the PowerShell module added Google.Cloud.Datastore.V1 as a .Net Package dependency it would make it a lot easier to find said DLL and dependencies and use them in PowerShell.

**Comment by quoctruong** [comment]
@adarobin Have you tried using `Install-Package` cmdlet to install the nuget package Google.Cloud.Datastore.V1 instead?

**Comment by adarobin** [comment]
@quoctruong Unfortunately, that isn't really a workable solution as all of the dependencies need to be in the same directory to be able to load them.  Additionally, you also have to make sure you aren't loading any DLLs that will conflict with ones the module is loading.

**Comment by quoctruong** [comment]
@adarobin I see. Unfortunately, we don't want to include extra dlls that the module is not using because this will increase the size of the module. Also, the module is included in the Cloud SDK so that will also include the size of the SDK.

**Comment by adarobin** [comment]
@quoctruong I understand, one last pitch though.  Don't think of it as adding unused modules, but as adding additional PowerShell functionality with minimal effort :-D

**Comment by quoctruong** [comment]
@adarobin Another option is you can help writing a Google Cloud Datastore cmdlet too. I can help you with the process if you want to do that. What do you think?
