### ISSUE TITLE
Set custom memory for a instance will be good

### ISSUE THREAD

**Issue by cmreddyv** [GoogleCloudPlatform/google-cloud-powershell#572]
If i want to add custom memory to the instance, there is no way now to add via powershell, it will be a great feature if we can add that

**Comment by quoctruong** [comment]
@cmreddyv Are you referring to [this](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#extendedmemory)?

**Comment by cmreddyv** [comment]
@quoctruong , yes we should have the ability to edit the memory of the machines using PowerShell, similar to gcloud --custom-cpu 4 --custom-memory 5376MB

**Comment by cmreddyv** [comment]
any update, you would like to give to us?

**Comment by quoctruong** [comment]
@cmreddyv Apologize for the delay, we are focusing mostly on maintenance and bug fixing at this time. I will investigate this today.

**Comment by cmreddyv** [comment]
@quoctruong , is this fixed?

**Comment by quoctruong** [comment]
@cmreddyv, this is fixed in the repository. We plan to do a release to the PowerShell Gallery tomorrow.

**Comment by quoctruong** [comment]
@cmreddyv, the latest module is now released on the PowerShellGallery. Please run `Update-Module GoogleCloud` to get the latest version with the fix!
