### ISSUE TITLE
Get-GcsObject :  ErrorAction preference not taking effect

### ISSUE THREAD

**Issue by rajaprad** [GoogleCloudPlatform/google-cloud-powershell#587]
**Module** - 1.0.1.2

**Command**:
Get-GcsObject -Bucket pradebbanbucket -ObjectName summa -ErrorAction **SilentlyContinue**
Get-GcsObject : Storage object 'summa' does not exist.
At line:1 char:1
+ Get-GcsObject -Bucket pradebbanbucket -ObjectName summa -ErrorAction  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (summa:String) [Get-GcsObject], ItemNotFoundException
    + FullyQualifiedErrorId : ObjectNotFound,Google.PowerShell.CloudStorage.GetGcsObjectCmdlet

**Issue**
-ErrorAction SilentlyContinue does not suppress the error!

**Comment by ILMTitan** [comment]
It looks like it is throwing a terminating error without a good reason. I will change that.

**Comment by quoctruong** [comment]
@rajaprad the fix is now available in version 1.0.1.14 of the module
