### ISSUE TITLE
Browsing storage buckets in gs: causes PowerShell to crash

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-powershell#594]
I am using version 1.0.1.4 (I also saw this with 1.0.0.9).

Repo steps:
1. Open PowerShell and 'cd gs:/'
2. Run a few commands.
3.  Let the terminal sit for a minute or two and the terminal will close unexpectedly.

**Comment by quoctruong** [comment]
@talarico Is it possible to include the list of commands that you run? Thanks!

**Comment by iantalarico** [comment]
@quoctruong It's done it for almost all combinations I tried.

I just did: ls, ls, cd, cd, cd, ls, cat, ls, cd, cd 

After the last cd I waited about 90 seconds and the windows just closed.

**Comment by ILMTitan** [comment]
It looks to me like an exception on [line 1156 of GoogleCloudStorageProvider.cs](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/753863c793823d38fe3f4b11336c3b9f9b90629c/Google.PowerShell/Provider/GoogleCloudStorageProvider.cs#L1156) can cause a hang at [line 1169](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/753863c793823d38fe3f4b11336c3b9f9b90629c/Google.PowerShell/Provider/GoogleCloudStorageProvider.cs#L1169).
