### ISSUE TITLE
Support Kubernetes Engine

### ISSUE THREAD

**Issue by Satak** [GoogleCloudPlatform/google-cloud-powershell#606]
Is Kubernetes Engine support in the pipeline? It would be really useful to have Powershell Cmdlets for anything related to Kubernetes Engine, e.g. Deployments, Services, Secrets, Configmaps, Volumes, Claims, etc.

**Comment by quoctruong** [comment]
@Satak We do have cmdlets to manage Kubernetes Clusters. We don't have plan for supporting other Kubernetes Engine related things like deploying, etc.
