### ISSUE TITLE
Get-GceMetadata fails with 403 on subsequent runs (works the first time)

### ISSUE THREAD

**Issue by Coleeb** [GoogleCloudPlatform/google-cloud-powershell#607]
At some point between release 177.0.0 and 193.0.0 (latest) of the gCloud SDK, this cmdlet no longer works after a single invocation.

To reproduce: 

On a Windows VM, open Powershell and run: 

Get-GceMetadata

It should return the top level metadata categories. Re-run the same command and you *should* see the same output as before, but instead there is an unformatted 403 error. Get-GceMetadata will work again (1 time) in a new Powershell window.

Here's an example output:

PS C:\Users\bob> Get-GceMetadata
instance/
oslogin/
project/
 
PS C:\Users\bob> Get-GceMetadata
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{mar
gin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/error
s/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:
none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0
}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-le
ft:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/
2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googl
elogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:ur
l(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 1
00%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/computeMetadata/v1/?</code> from this server. Missing Metada
ta-Flavor:Google header. <ins>That’s all we know.</ins>

**Comment by quoctruong** [comment]
@Coleeb Thanks for reporting the issue. Do you know which version of the module you are using? (You can see this with `Get-Module GoogleCloud` command when the module is loaded).

**Comment by quoctruong** [comment]
@Coleeb This is now fixed in version 1.0.1.7. Please give it a try!
