### ISSUE TITLE
Extend New-GceAttachedDiskConfig to support local SSD scratch disks

### ISSUE THREAD

**Issue by pjmcc2009** [GoogleCloudPlatform/google-cloud-powershell#615]
Currently there is no way to use the Google Cloud Powershell tools to create a GCE instance with one or more local SSD scratch disks.  This can be implemented by extending the New-GceAttachedDiskConfig cmdlet to include support for local SSD disks.

Proposed solution:

Extend the parameter set for New-GceAttachedDiskConfig to include a single parameter ScratchDiskZone which takes in a GCE zone as input.  The cmdlet then returns a AttachedConfig object of type SCRATCH and diskType /zones/{zone}/diskTypes/local-ssd

**Comment by quoctruong** [comment]
This fix is available in version 1.0.1.8 of the module.
