### ISSUE TITLE
Powershell core support

### ISSUE THREAD

**Issue by Satak** [GoogleCloudPlatform/google-cloud-powershell#619]
Why the Powershell module is for Windows Powershell and not for cross platform Powershell core?

**Comment by quoctruong** [comment]
@Satak The module actually works on both .NET and .NET Core. It should work on PowerShell Core as well. Did you have any problems running it?

**Comment by Satak** [comment]
Oh ok, I haven't tried it on Linux because the documentation keeps mentioning Windows this and that. Maybe there should be explicit info that it's for Powershell core and not only for Powershell windows.

**Comment by quoctruong** [comment]
@Satak Thanks for the suggestion. We will update the documentation.

**Comment by quoctruong** [comment]
Closed as the document at https://cloud.google.com/tools/powershell/docs/ has been updated.
