### ISSUE TITLE
Upload a file with ObjectNamePrefix

### ISSUE THREAD

**Issue by justlearntutors** [GoogleCloudPlatform/google-cloud-powershell#621]
I am trying to upload a file.

WORKS
New-GcsObject -Bucket "ssl-images-justlearn" -File "C:\CodeDeployWindowsDemo\EnviromentSetup\publishAppRaw\wwwroot\stylesheet.min.css"

ERROR
New-GcsObject -Bucket "ssl-images-justlearn" -File "C:\CodeDeployWindowsDemo\EnviromentSetup\publishAppRaw\wwwroot\stylesheet.min.css" -ObjectNamePrefix "article"

**Comment by justlearntutors** [comment]
SOLUTION
New-GcsObject -Bucket "ssl-images-justlearn" -File "C:\CodeDeployWindowsDemo\EnviromentSetup\publishAppRaw\wwwroot\stylesheet.min.css" -ObjectName "article\stylesheet.min.css"

**Comment by justlearntutors** [comment]
How do I add cache headers for file?

**Comment by quoctruong** [comment]
@justlearntutors, you can use the `-Metadata` parameter to add metadata to the object being uploaded. For example: `New-GcsObject -Bucket my-bucket "new-object" -Metadata @{"Content-Type" = "image/png"}`.

You can read more about this cmdlet [here](https://googlecloudplatform.github.io/google-cloud-powershell/#/google-cloud-storage/GcsObject/New-GcsObject)
