### ISSUE TITLE
[Feature requiest]Set resource labels

### ISSUE THREAD

**Issue by Wasapl** [GoogleCloudPlatform/google-cloud-powershell#622]
Is there a way to set labels for resources like snapshots and images ?

**Comment by quoctruong** [comment]
@Wasapl, this is currently not supported in most of the cmdlets (only BigQuery and Log cmdlets have these labels).

**Comment by Wasapl** [comment]
In this case it's a feature request )))

**Comment by quoctruong** [comment]
@Wasapl This is available in the latest powershell release.
