### ISSUE TITLE
Content-Encoding gzip error

### ISSUE THREAD

**Issue by justlearntutors** [GoogleCloudPlatform/google-cloud-powershell#626]
Here is my command for Powershell

New-GcsObject -Bucket ssl-images-justlearn -ContentType application/javascript -ObjectName $JsStr -Metadata @{ "Content-Encoding" = "gzip"} -File C:\Users\Philip\source\repos\Justlearn\Justlearn\wwwroot\script.min.js.gz -Force

I want to add gzip for Content-Type

The result is shown here. https://imgur.com/a/7mtfvtw

How can I solve?

Content-Type gzip is added in the wrong place.

**Comment by quoctruong** [comment]
@justlearntutors I don't think Content-Type can be gzip (gzip is Content-Encoding, not the underlying content type). You can read more about that under the Content-Encoding section [here](https://cloud.google.com/storage/docs/metadata).

**Comment by justlearntutors** [comment]
How can I add Content-Encoding in the right place?

-Metadata @{ "Content-Encoding" = "anything"}

See image.
![Image of Cloud](https://ssl.justlearn.com/0test/google-cloud-content-type-paint.png)

**Comment by quoctruong** [comment]
@justlearntutors I did some investigation and turns out this is a bug in the cmdlet. We will fix this in the next release. Thanks for finding this out!
