### ISSUE TITLE
Update Module GoogleCloud

### ISSUE THREAD

**Issue by justlearntutors** [GoogleCloudPlatform/google-cloud-powershell#628]
I want to update GoogleCloud version 1.0.1.8 to newest version.

I am trying to update Module GoogleCloud, but there have been errors.

I have downloaded Google Cloud SDK.

I run Update-Module GoogleCloud in PowerShell.

Error message.
Update-Module : Module 'GoogleCloud' was not installed by using Install-Module, so it cannot be updated.
At line:1 char:1
+ Update-Module GoogleCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (GoogleCloud:String) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : ModuleNotInstalledUsingInstallModuleCmdlet,Update-Module

I run Install-Module GoogleCloud -Force in PowerShell.

Error message.
PackageManagement\Install-Package : The module 'GoogleCloud' cannot be installed or updated because the authenticode
signature of the file 'GoogleCloud.psd1' is not valid.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage

I run gcloud components update in Powershell. Module GoogleCloud is not getting updated.

How can I update module?

**Comment by quoctruong** [comment]
@justlearntutors It appears we have an invalid authenticide signature for this version. We will fix that in the next release. It should be out next week. Sorry for the inconvenience.

In the meantime, a temporary workaround/hack if you want to use the 1.0.1.9 version is to use `Save-Module` to download this module to a location on your computer and use `Import-Module` to import and use it the module directly.

**Comment by quoctruong** [comment]
@justlearntutors I have released the 1.0.1.10 version of GoogleCloud to the PowerShellGallery. You can now update it with `Update-Module`. Feel free to open this again if it does not work for you. Thanks for your patience and sorry for the inconvenience.
