### ISSUE TITLE
Need Powershell cmdlets for Billing.

### ISSUE THREAD

**Issue by kharadzv** [GoogleCloudPlatform/google-cloud-powershell#638]
At present, the Billing information of the GCP Compute Engine is only possible via REST API's. Could not find related Powershell cmdlets anywhere on the https://googlecloudplatform.github.io/google-cloud-powershell/#/ page.

**Comment by quoctruong** [comment]
@kharadzv Currently the project is in maintenance mode and we do not plan to support adding any new cmdlets. Pull requests are welcomed though if you want to add new cmdlets for this.
