### ISSUE TITLE
Commands not working in powershell

### ISSUE THREAD

**Issue by Shaun-Harrison** [GoogleCloudPlatform/google-cloud-powershell#641]
I'm running a GCE Instance for some time now, with some powershell scripts that use the powershell cloud commands. 
Recently the scripts are failing so tried running the cloud commands manually , for example get-gceinstance 

I keep getting the same generic error no matter the command
![image](https://user-images.githubusercontent.com/46562010/73181502-3d7ae300-410f-11ea-9de4-cb8567e831fa.png)

When I use the sdk shell it works fine

I've also checked that the module is loaded and all appears to be fine
![image](https://user-images.githubusercontent.com/46562010/73181568-5c797500-410f-11ea-8734-a8088e92b97b.png)

**Comment by sspage** [comment]
You've installed the Google Cloud SDK?  You might try re-running gcloud init as it is a dependency.

**Comment by Shaun-Harrison** [comment]
Hello - Yes already had it installed, and even uninstalled and reinstalled to try getting it to work - as mentioned in my post, everything works find in the sdk shell, its just powershell that isn't working

**Comment by Shaun-Harrison** [comment]
> You've installed the Google Cloud SDK?  You might try re-running gcloud init as it is a dependency.

In case your wondering, issue was due to tls 1.0 & tls 1.1 being disabled
