### ISSUE TITLE
Consider supporting gs://bucket/blob/name style paths in the GCS cmdlets

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/google-cloud-powershell#90]
gsutil supports using gs:// paths to talk about buckets and blobs in those buckets. This abstraction is also more manageable than providing the bucket and the file name as different parameters. 

Consider supporting gs:// paths in the GCS cmdlets to allow a certain level of interoperability between gsutil and the cmdlets. If the gs:// paths were supported the Visual Studio extension could create said paths and put them in the clipboard when users selected files or buckets in the Cloud Explorer, and could be pasted in the PowerShell terminal to use in the command line construction.

**Comment by ILMTitan** [comment]
The provider is giving us capabilities very much like this. I'm not sure duplicating it in the cmdlets in necessary.
