### ISSUE TITLE
Add vs. New vs. Create

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#92]
in GCE, you Add a new Instance
in GCS, you New a new bucket (not a verb)
Should they be harmonized?

**Comment by ILMTitan** [comment]
During our usability studies, it seemed as though New was slightly preferred to Add, but was not significant barrier to usability.

**Comment by ILMTitan** [comment]
If we ever decide this actually leads to confusion, we can add cmdlet aliases. For now, I am closing this issue.
