### ISSUE TITLE
New-GcsObject error message when trying to upload folder hard to understand

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#93]
Trying to upload a folder:
New-GcsObject -bucket abucket -name aname -file path/to/a/dir

Error thrown says `File not found`, I would have expected something along the lines of `New-GcsObject only supports file upload, path/to/a/dir is a folder`

**Comment by quoctruong** [comment]
We have the ability to upload a folder with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/329 so this won't error out anymore.
