### ISSUE TITLE
Simplify the creation of a new Windows Server 2012 VM

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#99]
in glcoud:
`gcloud compute instances create example-instance --image windows-2012-r2`
The only thing I have to know is the image name **windows-2012-r2**, and then to pass the name

in PowerShell cmdlets:
`$images = Get-GceImage -Project "windows-cloud"`
`$winimage = ($images[$images.length-1]).selfLink`
`$config = New-GceInstanceConfig -DiskImage $winimage -Name Yann-machine -MachineType n1-standard-1`
`Add-GceInstance -Instance $config`

I have to know the **image selflink** (equivalent to the windows-2012-r2, although likely way harder to remember and type from memory), and the **machine type**

Suggestions
`Add-GceInstance -name Yann-machine -image https://www.googleapis.com/compute/v1/projects/windows-cloud/global/images/windows-server-2012-r2-dc-v20160623` with default n1-standard-1. Might write into the standard output to tell the user about the default the command assumed implicitely.

**Comment by ILMTitan** [comment]
As it stands now.
1 is solved.
2. The instance config half is solved. The image object half is a design decision I am hesitant to change. Getting the image means knowing it is there before making the instance.
3. Fixed.
4. Fixed. Now named -InstanceConfig.
